### ISSUE TITLE
null author in episode threads

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-miner#16]
This causes issues when trying to use this backend for dev work.

I can look into it this. In prod it is (several elements omitted):

```json
"author": {
            "name": "Software Daily",
            "username": "SoftwareDaily"
}
```

**Comment by jasonify** [comment]
Ahh, yeah, you will need to create this user locally.  Which file are you trying to run, to create the forum threads for each episode right?

**Comment by joshmorel** [comment]
Yes it's `makeThreadForEpisodes`. I figure anyone using this shouldn't need to create the user manually first. Working on this now, however, it does't seem like a typical workflow to insert a doc with an `_id` (like the `THREAD_AUTHOR_ID`). I'm wondering if using something that _should_ be unique (like `username`) to find the user document and insert it if it doesn't exist would be better and otherwise just continue would be better.

**Comment by jasonify** [comment]
I like the idea about having it check for that user first. I think checking for both UID and username and having it exit saying: "Please do x, y, z" would be good?  This way it would be an extra check and limit errors between having "Test_Account" litter the production one by accident (this is mostly a precaution for me of course).

**Comment by jasonify** [comment]
Let's keep brainstorming on this. I think we are getting close.

So currently it's already a little error prone. 

But I think a pretty simple solution would be to check if there is no ID passed. Then it checks if a username with SoftwareDaily exists, if it does, it throws an error and exists saying: "You are probably pointing to production or already have that user but just need to set the `THREAD_AUTHOR_ID`  , here is some debug info."

This will prevent production from having a random user created if the script is ran incorrectly. 

What do you think?

**Comment by joshmorel** [comment]
I'm wondering then, if `SoftwareDaily` is an app constant for the user making the episode threads does it even make sense to have an environment variable? Should it just be hard coded into the script then --> find the user `SoftwareDaily` - use the id for inserting episode threads. In any environment where it does not exist - for example `dev` - then create the user and use that id.

**Comment by joshmorel** [comment]
Pretty much done, however, was looking for a way to get `process.exit()` working in there. The problem is that we have promises (from `monk`) mixed with callbacks. This is hard to work with ... ideally we'd be returning promises from all the functions (whether using `Bluebird` or the native `Promise`) instead of using callbacks. With this change, `process.exit()` could work.

I can put this all into one PR or just get the author part working without `process.exit()` and add that later. Let me know your preference.
