### ISSUE TITLE
Mining Transcripts

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-miner#3]
Currently some episodes have transcripts, some don't. The transcripts are attached to the episode as PDF [like here](https://softwareengineeringdaily.com/2017/10/28/cryptoeconomics-with-vlad-zamfir/).

**Comment by crablar** [comment]
@erikawho are there still some episodes where the transcript is pasted into the post itself?

**Comment by erikawho** [comment]
No, the transcripts that are on the site are all PDF attachments.
